### ISSUE TITLE
Copy Review

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-newsletters#217]
There are a few minor inconsistencies in button text and warning messages. Could use a thorough review.

**Comment by laurelfulford** [comment]
I went through screen by screen -- hopefully how I divided this makes sense!

## Creating a Newsletter

![image](https://user-images.githubusercontent.com/177561/85789480-872e2080-b6e3-11ea-92ee-2194ed777691.png)

* Buttons: "Start From Scratch", "Use Selected Layout" -- I feel like these should not be title case, like "Start from scratch" and "Use selected layout". On WP.com, when picking a layout for a new page, it will capitalize the layout name, but not everything -- like "Use Blog layout".

## Editing a Newsletter

### Newsletter (Panel)

![image](https://user-images.githubusercontent.com/177561/85789577-b8a6ec00-b6e3-11ea-9af2-d63cdba72e31.png)

* Panel name: What do you think about making panel name more descriptive? ("Newsletter Settings"? ); or something specific to recipients, since the panel is only for setting who the email is going to, who it's from and what the subject is (I can't think of a better term though).
* Mailchimp calls a similar panels "Header Info"; it's technically correct for emails, but I feel like that's not a super-familiar term.
* What do you think about changing the label "Subject" to "Email subject"? 
* For the sender -- what about "Sender Name" and "Sender Email" instead of the "From" and then two fields? Then all of the labels can be the same weight. 

### Styling (Panel)

![image](https://user-images.githubusercontent.com/177561/85759600-f7c64480-b6c5-11ea-91b2-5cf885e33a96.png)

* Panel name: Gutenberg uses "Color settings" and "Text settings" for blocks; what about "Style settings" for the panel name? Or "Newsletter Styles" to go with WP.com's "Global Styles"? This could also help distinguish it from the Styles panel that appears when you select an individual block. 

* The Newsletters currently use "Headings font" and "Body font"; "Headings" should probably just be "Heading"; if we wanted to line this up with the WP.com labels for FSE, I'd also recommend replacing "Body" with "Base":

Newsletters:
![image](https://user-images.githubusercontent.com/177561/85763068-327dac00-b6c9-11ea-89a2-dd1b6684d27e.png)

WP.com Global Styles:
![image](https://user-images.githubusercontent.com/177561/85762952-1a0d9180-b6c9-11ea-9cd2-2209b01d6082.png)

### Testing (panel)

![image](https://user-images.githubusercontent.com/177561/85789867-2b17cc00-b6e4-11ea-807d-57f58647d47d.png)

* I think "Send Test" might be a more descriptive panel name
* The text "Send a test to" and "Use commas to separate multiple emails." were both copied from MailChimp; the only bit that strikes me as weird is "Send a test to" matches the sentence-like field labeling MailChimp does, but we're not really doing. "Send test to" might match a bit better, or "Test recipient"? 
* Button: "Send a Test Email" --> "Send test"? (New verbiage copied from MailChimp and Campaign Monitor, and switched away from title case to match other buttons).

### Layout (panel)

![image](https://user-images.githubusercontent.com/177561/85789904-3cf96f00-b6e4-11ea-95a2-cd560bbe543b.png)

The buttons in this section trigger the following alerts:

**Save new layout**

![image](https://user-images.githubusercontent.com/177561/85789984-5995a700-b6e4-11ea-8c27-bbfba4e30ac5.png)

What about "Layout name" instead of "Title" for the label?

**Update Layout**

![image](https://user-images.githubusercontent.com/177561/85790010-62867880-b6e4-11ea-802a-8afc9472511b.png)

Opens system dialog, not WordPress one, unlike the other two - they all seem to serve a similar purpose, is it possible to make them all the same? It's also worth noting the button order is different (with Cancel first for this one, and second for the other two). 

**Reset newsletter layout**

![image](https://user-images.githubusercontent.com/177561/85790042-7336ee80-b6e4-11ea-8110-958b21b4bb12.png)

I feel like the title for this dialog is confusing, because "Override newsletter content?" is like it's confirming that you want to take that action, but it's not actually the action you picked ("Reset newsletter layout"). What about something like "Your changes will be lost" or "Are you sure?"



**Settings**
Not really a copy comment, but what do you think about adding info about how to populate each of these fields, even just linking off to the appropriate screens for each item?
