### ISSUE TITLE
Featured image options

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-newsletters#423]
Posts have several featured image options that publishers find useful, such as how or whether to display the featured image in the single view. Newsletters should have the same or similar options, especially the "hide" option as showing the featured image probably isn't appropriate for most newsletters, but it's still useful for them to have a featured images for archive pages and homepage posts blocks.

**Comment by roundtablemark** [comment]
Better control of the "featured image" function would give us better options as figure out how to post our daily newsletter on the site. Since we can't hide the featured image now, it displays huge at the top of the newsletter, which is undesirable both for email subscribers and people who would view it on the site.
