### ISSUE TITLE
Breaking WooCommerce Product Category Pages

### ISSUE THREAD

**Issue by dnalla1928** [Automattic/newspack-newsletters#637]
WooCommerce product category is not showing any products.  The catalog visibility is set to catalog and search and products are in stock.  Mississippi Today first reported it, and part of my troubleshooting led me to look at other sites.  So I checked Plainsman Herald, The Pavlovic Today, and Grice Connect and all of them are experiencing the same result.

I spun up a clone site and disabled all plugins 1-by-1.  Found that Newsletters was causing the issue.  Reproduced it on the live site by only disabling Newsletters and got the same result.

Related: https://a8c.slack.com/archives/C01C378QWRX/p1638476150117800

**Comment by gamebits** [comment]
This issue is still happening. It first appeared in Newspack Newsletters v1.50.0.

Steps to reproduce:

1. Install Newspack Newsletters [v1.47.2](https://github.com/Automattic/newspack-newsletters/releases/tag/v1.47.2).
2. View a WooCommerce product category, such as https://juiced.gs/store/category/software/ — it will list the products available in that category.
3. Update Newspack Newsletters to [v1.48.0](https://github.com/Automattic/newspack-newsletters/releases/tag/v1.48.0) or later.
4. View the WooCommerce product category. It now indicates that no products are found.

I suspect [this PR](https://github.com/Automattic/newspack-newsletters/issues/863) is related.

Screenshot with v1.47.2 installed:

![v1472](https://user-images.githubusercontent.com/12199101/228710191-4f8fcb22-8661-4af2-b8ee-4166f2bb5003.jpg)

Screenshot with v1.50.0:

![v1500](https://user-images.githubusercontent.com/12199101/228710207-5f95a9a8-3a82-4982-a83e-9efc55a99b01.jpg)

**Comment by gamebits** [comment]
Also in Asana: 1200550061930446-as-1204312758836599
